PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Users (
    UID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(255),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Games (
    GID INTEGER PRIMARY KEY AUTOINCREMENT,
    GameTime DATETIME NOT NULL,
    Location VARCHAR(255),
    Status VARCHAR(20) CHECK (Status IN ('scheduled', 'completed')) NOT NULL
);

CREATE TABLE IF NOT EXISTS GamePlayers (
    GID INTEGER,
    UID INTEGER,
    Team INTEGER,
    Score INTEGER,
    IsWinner BOOLEAN,
    PRIMARY KEY (GID, UID),
    FOREIGN KEY (GID) REFERENCES Games(GID),
    FOREIGN KEY (UID) REFERENCES Users(UID)
);

CREATE TABLE IF NOT EXISTS Conversations (
    CID INTEGER PRIMARY KEY AUTOINCREMENT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ConversationParticipants (
    CID INTEGER,
    UID INTEGER,
    PRIMARY KEY (CID, UID),
    FOREIGN KEY (CID) REFERENCES Conversations(CID),
    FOREIGN KEY (UID) REFERENCES Users(UID)
);

CREATE TABLE IF NOT EXISTS Messages (
    MessageID INTEGER PRIMARY KEY AUTOINCREMENT,
    CID INTEGER NOT NULL,
    SenderUID INTEGER NOT NULL,
    Content TEXT NOT NULL,
    SentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CID) REFERENCES Conversations(CID),
    FOREIGN KEY (SenderUID) REFERENCES Users(UID)
);
